---
title: "Welcome to my website"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Introduction

Hi! I’m Peng Su, second year Master students in Biostatistics at Columbia University, and majored in Bioinformatics as an undergraduate at Xi’an Jiaotong-Liverpool University. I’m really interested in using high-throughput and multi-omics data to investigate biological functions especially tumor immune related pathways and discover novel therapeutic loci and signatures.

I have six years of experience using R, along with proficiency in basic Python, MATLAB, and SQL. My research experience includes building cancer immune prognostic models using genomic data, summarizing immune-related signatures through big data analysis and leveraging existing databases. Currently, I am participating in a research project that investigates the dynamic fluctuations of gut microbiota in human and baboon host, as well as the functional factors influencing microbial abundance.

# Publication 

* Su, P., Tchourine, K., Vitkup, D. (2024). Ecological Scaling of Temporal Fluctuations with Bacterial Abundance in Gut Microbiota Depends on Functional Properties of Individual Microbial Species and Bacterial Communities. bioRxiv, 625948. [https://www.biorxiv.org/content/10.1101/2024.11.28.625948v1](https://www.biorxiv.org/content/10.1101/2024.11.28.625948v1)

* Li, J., Su, P., Li, T., Hao, Y., Wang, T., Fu, L., & Liu, X. (2024). The Role and Clinical Relevance of Glycolysis-Associated Genes on Immune Infiltration in Hepatocellular Carcinoma. Journal of cellular biochemistry, 125(8), e30620. [https://doi.org/10.1002/jcb.30620](https://doi.org/10.1002/jcb.30620)

# More infromation
For more detail information please refer 

* [CV](image/CV_Peng_Su.pdf)

* [code sample]

* [Github](http://github.com/PengSu19/)

* [email](mailto:<ps3395@cumc.columbia.edu>)

Wish you have a great day!